# ==========================================
# Steam 平台反向代理配置
# ==========================================

# Steam 社区
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name *.steamcommunity.com steamcommunity.com;

    include cert.conf;

    location ~* ^.*(discussions|comment|forum).*$ {
        proxy_pass https://steam-community-302;
        proxy_next_upstream error timeout http_403 http_429 http_500 http_502 http_503 http_504;
        proxy_http_version 1.1;
        proxy_set_header Host "steamcommunity.com";
        proxy_set_header User-Agent "${http_user_agent} Googlebot/2.1 (+http://www.google.com/bot.html)";
        proxy_ssl_server_name on;
        proxy_ssl_name "statuspage.akamaized.net";
    }

    location / {
        proxy_pass https://steam-community;
        proxy_next_upstream error timeout http_403 http_429 http_500 http_502 http_503 http_504;
        include shared-proxy-empty-sni.conf;
        proxy_read_timeout 60s;
    }
}

# Steam 商店与结账
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name store.steampowered.com checkout.steampowered.com steampowered.com;

    include cert.conf;

    location / {
        proxy_pass https://steam-store;
        proxy_next_upstream error timeout http_403 http_429 http_500 http_502 http_503 http_504;
        include shared-proxy-empty-sni.conf;
        proxy_read_timeout 60s;
    }
}

# Steam 登录与 API 支持
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name api.steampowered.com login.steampowered.com help.steampowered.com;

    include cert.conf;

    location / {
        proxy_pass https://steam-store;
        proxy_next_upstream error timeout http_403 http_429 http_500 http_502 http_503 http_504;
        include shared-proxy-empty-sni.conf;
        proxy_read_timeout 60s;
    }
}

# Steam 静态图片与资产 CDN
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name community.akamai.steamstatic.com community.steamstatic.com;

    include cert.conf;

    location / {
        proxy_pass https://steam-akamai-cdn;
        include shared-proxy-empty-sni.conf;
        proxy_set_header Host "community.steamstatic.com";
        proxy_next_upstream error timeout http_403 http_429 http_500 http_502 http_503 http_504;
    }
}
