# ==========================================
# GitHub 平台反向代理配置
# ==========================================

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name github.com www.github.com api.github.com codeload.github.com gist.github.com;

    include cert.conf;

    location / {
        proxy_pass https://github-web;
        include shared-proxy-empty-sni.conf;
        proxy_next_upstream error timeout http_403 http_429 http_500 http_502 http_503 http_504;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name raw.githubusercontent.com user-images.githubusercontent.com objects.githubusercontent.com;

    include cert.conf;

    location / {
        proxy_pass https://github-raw;
        include shared-proxy-empty-sni.conf;
        proxy_next_upstream error timeout http_403 http_429 http_500 http_502 http_503 http_504;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
