# ==========================================
# Hugging Face 平台反向代理配置
# ==========================================

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name huggingface.co hf.co cdn-lfs.huggingface.co;

    include cert.conf;

    location / {
        proxy_pass https://huggingface-web;
        include shared-proxy-empty-sni.conf;
        proxy_next_upstream error timeout http_403 http_429 http_500 http_502 http_503 http_504;
        proxy_read_timeout 180s;
        proxy_send_timeout 180s;
    }
}
